[project]
name = "fno-mag"
version = "0.1.0"
description = "FNO for predicting magnitude from GH CSVs"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.24",
    "pandas>=1.5",
    "tqdm",
    "neuraloperator",
    "matplotlib",
    "onnxscript",
    "onnx",
    "onnxruntime",
]

[dependency-groups]
dev = []

[tool.uv]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }
